<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class QuoteCostAnalysis extends Model
{
    use HasFactory;

    protected $fillable = [
        'quote_id',
        'crm_project_id',
        'quote_item_id',
        'description',
        'cost_amount',
        'is_auto_generated',
        'work_description',
    ];

    protected $casts = [
        'cost_amount' => 'decimal:2',
        'is_auto_generated' => 'boolean',
    ];

    /**
     * Relazione con Quote
     */
    public function quote(): BelongsTo
    {
        return $this->belongsTo(Quote::class);
    }

    /**
     * Relazione con CrmProject
     */
    public function crmProject(): BelongsTo
    {
        return $this->belongsTo(CrmProject::class, 'crm_project_id');
    }

    /**
     * Relazione con QuoteItem
     */
    public function quoteItem(): BelongsTo
    {
        return $this->belongsTo(QuoteItem::class);
    }

    /**
     * Scope per costi auto-generati
     */
    public function scopeAutoGenerated($query)
    {
        return $query->where('is_auto_generated', true);
    }

    /**
     * Scope per costi manuali
     */
    public function scopeManual($query)
    {
        return $query->where('is_auto_generated', false);
    }

    /**
     * Scope per progetto
     */
    public function scopeForProject($query, $projectId)
    {
        return $query->where('crm_project_id', $projectId);
    }
}

