<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class FreelanceAiAssistantController extends Controller
{
    private const GROQ_API_URL = 'https://api.groq.com/openai/v1/chat/completions';
    private const MODEL         = 'llama-3.3-70b-versatile';
    private const MAX_TOKENS    = 1400;
    private const TEMPERATURE   = 0.45;
    private const TIMEOUT_S     = 28;
    private const MAX_HISTORY   = 10;

    /**
     * POST /api/freelance/ai-assistant/chat
     *
     * Returns { answer: string, actions?: Action[] }
     * where Action = { type, path|text|selector, delay? }
     */
    public function chat(Request $request): JsonResponse
    {
        $request->validate([
            'message'             => ['required', 'string', 'max:2000'],
            'context'             => ['sometimes', 'array'],
            'history'             => ['sometimes', 'array', 'max:' . self::MAX_HISTORY],
            'history.*.role'      => ['required_with:history', 'in:user,assistant'],
            'history.*.content'   => ['required_with:history', 'string', 'max:3000'],
            'activeElement'       => ['sometimes', 'array'],
            'pageSnapshot'        => ['sometimes', 'string', 'max:3000'],
        ]);

        /** @var \App\Models\User $user */
        $user          = $request->user();
        $message       = trim($request->input('message', ''));
        $context       = $request->input('context', []);
        $history       = array_slice($request->input('history', []), -self::MAX_HISTORY);
        $activeElement = $request->input('activeElement', []);
        $pageSnapshot  = trim($request->input('pageSnapshot', ''));

        $systemPrompt = $this->buildSystemPrompt($user, $context, $activeElement, $pageSnapshot);
        $messages     = $this->buildMessages($systemPrompt, $history, $message);

        $apiKey = config('services.groq.api_key');
        if (empty($apiKey)) {
            return response()->json(['answer' => 'AI non configurata sul server.', 'actions' => []], 200);
        }

        try {
            $response = Http::withToken($apiKey)
                ->timeout(self::TIMEOUT_S)
                ->post(self::GROQ_API_URL, [
                    'model'           => self::MODEL,
                    'messages'        => $messages,
                    'temperature'     => self::TEMPERATURE,
                    'max_tokens'      => self::MAX_TOKENS,
                    'response_format' => ['type' => 'json_object'],
                ]);

            if (!$response->successful()) {
                Log::error('Groq API error (FreelanceAiAssistant)', [
                    'status' => $response->status(),
                    'body'   => $response->body(),
                ]);
                return response()->json(['answer' => 'Errore dal servizio AI. Riprova.', 'actions' => []], 200);
            }

            $raw    = $response->json('choices.0.message.content', '{}');
            $parsed = is_string($raw) ? json_decode($raw, true) : $raw;

            $answer  = $parsed['answer']  ?? $parsed['risposta'] ?? $parsed['response'] ?? '';
            $actions = $parsed['actions'] ?? [];

            if (!$answer) {
                $answer = is_string($raw) ? $raw : 'Risposta non disponibile.';
            }

            // Sanitize actions: keep only known types
            $allowedTypes = ['navigate', 'fill_active', 'fill_element', 'highlight', 'scroll_to', 'click', 'speak'];
            $actions = array_values(array_filter(
                is_array($actions) ? $actions : [],
                fn($a) => is_array($a) && isset($a['type']) && in_array($a['type'], $allowedTypes, true)
            ));

            return response()->json(['answer' => $answer, 'actions' => $actions]);

        } catch (\Exception $e) {
            Log::error('FreelanceAiAssistant exception', ['error' => $e->getMessage()]);
            return response()->json(['answer' => 'Errore di connessione al servizio AI.', 'actions' => []], 200);
        }
    }

    // ─── Morning Brief ────────────────────────────────────────────────────────────

    /**
     * GET /api/freelance/ai-morning-brief
     *
     * Returns a daily brief generated by AI based on the user's task & project data.
     * Cached per user for 4 hours (based on date + user_id key).
     */
    public function morningBrief(Request $request): JsonResponse
    {
        /** @var \App\Models\User $user */
        $user = $request->user();

        $cacheKey  = "morning_brief_{$user->id}_" . now()->format('Y-m-d-H');
        $cached    = \Illuminate\Support\Facades\Cache::get($cacheKey);
        if ($cached) {
            return response()->json(array_merge($cached, ['cached' => true]));
        }

        // Gather real task data
        $today  = now()->setTimezone('Europe/Rome');
        $tasks  = \App\Models\CrmProjectTask::whereHas('project', function ($q) use ($user) {
                    $q->whereHas('members', fn($m) => $m->where('user_id', $user->id));
                })
                ->where('status', '!=', 'completed')
                ->select(['id', 'title', 'status', 'priority', 'due_date'])
                ->orderBy('due_date')
                ->limit(20)
                ->get();

        $overdue   = $tasks->filter(fn($t) => $t->due_date && $t->due_date < $today->toDateString());
        $dueToday  = $tasks->filter(fn($t) => $t->due_date === $today->toDateString());
        $dueWeek   = $tasks->filter(fn($t) => $t->due_date && $t->due_date > $today->toDateString() && $t->due_date <= $today->copy()->addDays(7)->toDateString());

        $summary = sprintf(
            "Oggi è %s. L'utente ha %d task totali attive. Scadute: %d. In scadenza oggi: %d. Scadenza entro 7 giorni: %d.\nTask in scadenza oggi: %s\nTask scadute: %s",
            $today->translatedFormat('l j F Y'),
            $tasks->count(),
            $overdue->count(),
            $dueToday->count(),
            $dueWeek->count(),
            $dueToday->pluck('title')->implode(', ') ?: 'nessuna',
            $overdue->pluck('title')->implode(', ') ?: 'nessuna',
        );

        $apiKey = config('services.groq.api_key');
        if (empty($apiKey)) {
            return response()->json(['headline' => 'Buona giornata!', 'body' => '', 'priority_task' => null, 'mood' => 'neutral']);
        }

        try {
            $response = Http::withToken($apiKey)
                ->timeout(20)
                ->post(self::GROQ_API_URL, [
                    'model'           => self::MODEL,
                    'temperature'     => 0.55,
                    'max_tokens'      => 500,
                    'response_format' => ['type' => 'json_object'],
                    'messages'        => [
                        ['role' => 'system', 'content' => <<<SYSTEM
Sei BackClub AI. Genera un briefing mattutino conciso per un freelance.
Dati del giorno: {$summary}
Utente: {$user->name}

Rispondi SOLO con JSON:
{
  "headline": "titolo breve e motivante max 60 caratteri (usa emoji)",
  "body": "2-3 frasi brevi su cosa fare oggi, pragmatiche e dirette",
  "priority_task": "titolo della task più urgente o null",
  "mood": "one of: productive|focused|gentle|urgent",
  "overdue_count": numero_intero,
  "today_count": numero_intero
}
SYSTEM
                        ],
                        ['role' => 'user', 'content' => 'Genera il brief del giorno.'],
                    ],
                ]);

            if (!$response->successful()) {
                return response()->json(['headline' => 'Buona giornata, ' . $user->name . '!', 'body' => '', 'priority_task' => null, 'mood' => 'productive', 'overdue_count' => $overdue->count(), 'today_count' => $dueToday->count()]);
            }

            $raw    = $response->json('choices.0.message.content', '{}');
            $parsed = json_decode($raw, true) ?? [];
            $parsed['overdue_count'] = $parsed['overdue_count'] ?? $overdue->count();
            $parsed['today_count']   = $parsed['today_count']   ?? $dueToday->count();

            \Illuminate\Support\Facades\Cache::put($cacheKey, $parsed, 60 * 4); // 4 hours

            return response()->json($parsed);
        } catch (\Exception $e) {
            Log::error('MorningBrief error', ['error' => $e->getMessage()]);
            return response()->json(['headline' => 'Buona giornata!', 'body' => '', 'priority_task' => null, 'mood' => 'neutral', 'overdue_count' => 0, 'today_count' => 0]);
        }
    }

    // ─── Helpers ─────────────────────────────────────────────────────────────────

    private function buildSystemPrompt(\App\Models\User $user, array $context, array $activeElement, string $pageSnapshot = ''): string
    {
        $now      = now()->setTimezone('Europe/Rome');
        $dateStr  = $now->translatedFormat('l j F Y, H:i');
        $userName = $user->name ?? 'Freelancer';
        $page     = $context['page']  ?? 'Freelance CRM';
        $path     = $context['path']  ?? '';
        $label    = $context['label'] ?? $page;

        $entityInfo = '';
        if (!empty($context['taskId']))    $entityInfo .= "\n- Task ID: #{$context['taskId']}";
        if (!empty($context['projectId'])) $entityInfo .= "\n- Progetto ID: #{$context['projectId']}";
        if (!empty($context['crmCode']))   $entityInfo .= "\n- CRM: {$context['crmCode']}";

        $activeInfo = '';
        if (!empty($activeElement['tag'])) {
            $activeInfo = "\n- Elemento attivo: <{$activeElement['tag']}>"
                . (!empty($activeElement['placeholder']) ? " placeholder=\"{$activeElement['placeholder']}\"" : '')
                . (!empty($activeElement['id']) ? " id=\"{$activeElement['id']}\"" : '');
        }

        $screenInfo = $pageSnapshot ? "\n\n**COSA VEDE L'UTENTE SULLO SCHERMO (DOM snapshot):**\n{$pageSnapshot}" : '';

        return <<<PROMPT
Sei BackClub AI, l'assistente intelligente integrato nel CRM freelance di backclub.it.
Sei come un assistente remoto iper-intelligente che può vedere lo schermo dell'utente e agire su di esso.

**UTENTE:** {$userName} — Freelance
**DATA/ORA:** {$dateStr}

**PAGINA CORRENTE:**
- Sezione: {$label}
- URL path: {$path}{$entityInfo}{$activeInfo}{$screenInfo}

**MAPPA NAVIGAZIONE CRM (route paths):**
- Dashboard principale: /freelance
- Lista progetti: /freelance/progetti  
- Lista task: /freelance/task
- Focus / concentrazione: /freelance/focus
- Chat: /freelance/chat
- Calendario: /freelance/calendario
- Impostazioni: /freelance/impostazioni
- Singola task: /freelance/task/{id}  (usa l'id numerico)
- Singolo progetto: /freelance/progetti/{id}

**AZIONI CHE PUOI ESEGUIRE (oltre a rispondere):**
1. `navigate` — Naviga a un'altra pagina: { "type": "navigate", "path": "/freelance/..." }
2. `fill_active` — Inserisci testo nell'input/textarea attualmente attivo/focalizzato dall'utente: { "type": "fill_active", "text": "testo da inserire" }
3. `highlight` — Evidenzia un elemento CSS: { "type": "highlight", "selector": "css-selector" }
4. `speak` — Leggi qualcosa ad alta voce: { "type": "speak", "text": "testo da leggere" }

**REGOLE FONDAMENTALI:**
- Parla SEMPRE in italiano, conciso e diretto.
- Se l'utente dice "portami a X", "vai a X", "apri X" → usa `navigate` con il path corretto.
- Se l'utente dice "scrivi / inserisci / compila [testo]" e c'è un input attivo → usa `fill_active`.
- Se l'utente fa domande su task, progetti, priorità → rispondi con consigli pratici.
- Sii come un collega esperto: diretto, pratico, utile.
- Se non conosci dati specifici (titolo task reale ecc.) dillo onestamente e offri alternative.

**FORMATO RISPOSTA — OBBLIGATORIO:**
Rispondi SEMPRE con JSON valido, struttura esatta:
{
  "answer": "risposta in italiano, usa markdown (grassetto, elenchi) per leggibilità, max 3 paragrafi",
  "actions": []
}

Dove `actions` è un array di azioni da eseguire (può essere vuoto).
Ogni azione può avere un campo opzionale `"delay": milliseconds` (default 700ms tra le azioni).

Esempio risposta con navigazione:
{
  "answer": "Certo! Ti porto subito alla lista dei tuoi progetti.",
  "actions": [{ "type": "navigate", "path": "/freelance/progetti", "delay": 800 }]
}

Esempio risposta con testo da inserire:
{
  "answer": "Ho inserito il testo nelle note per te.",
  "actions": [{ "type": "fill_active", "text": "Testo inserito dall'AI...", "delay": 500 }]
}

MAI includere azioni pericolose (delete, api calls esterne, ecc.).
MAI inventare path che non esistono nella mappa di navigazione.
PROMPT;
    }

    private function buildMessages(string $systemPrompt, array $history, string $userMessage): array
    {
        $messages = [['role' => 'system', 'content' => $systemPrompt]];

        foreach ($history as $turn) {
            $role    = $turn['role']    ?? 'user';
            $content = $turn['content'] ?? '';
            if ($content !== '') {
                $messages[] = ['role' => $role, 'content' => $content];
            }
        }

        $messages[] = ['role' => 'user', 'content' => $userMessage];

        return $messages;
    }
}
